Add merchant-House of Cards
firoorg/firo-site pull request #362
Opened 2024-02-24 20:44 UTC by ajaydono

2024-02-24 20:51 UTC, justanwar approved these changes

2024-02-25 10:07 UTC, erciccione approved these changes
Would be better to have the background of the logo transparent to stay consistent with the other merchants, but can be changed later.

2024-02-28 08:41 UTC, erciccione requested changes
There is typo in the name of the image, should be `houseofcards.png`.

2024-02-28 23:28 UTC, ajaydono reviewed
Fix typo

2024-02-29 07:52 UTC, erciccione approved these changes

2024-02-29 09:03 UTC, merged