New cfc members blog
firoorg/firo-site pull request #392
Opened 2024-05-05 14:53 UTC by ajaydono

2024-05-05 16:37 UTC, justanwar requested changes

2024-05-05 16:37 UTC, justanwar commented on _posts/2024-05-03-3rd-term-cfc-members-formed.md
> +1) To decide along with taking into account community feedback on how the Firo Community Fund should be utilised.
For numbered list, use `1. 2.` etc

2024-05-05 16:53 UTC, ajaydono reviewed
Done

2024-05-05 16:53 UTC, ajaydono commented on _posts/2024-05-03-3rd-term-cfc-members-formed.md
> +1) To decide along with taking into account community feedback on how the Firo Community Fund should be utilised.
Changes made

2024-05-06 06:10 UTC, erciccione approved these changes

2024-05-06 07:11 UTC, justanwar approved these changes

2024-05-06 07:12 UTC, merged