All the download page changes
firoorg/firo-site pull request #408
Opened 2024-07-11 16:50 UTC by rehrar

Updated Downloads page
- Removed Desktop and Mobile categories
- Replaced with Recommended wallets
- Removed Electron Wallet
- Updated hashes for new Campfire

2024-07-11 17:14 UTC, justanwar requested changes

2024-07-11 17:14 UTC, justanwar commented on _data/downloads.yml
The version for Electrum shouldn't change.

2024-07-12 08:05 UTC, erciccione reviewed
As a general note, I don't think it's a good idea to not have a "mobile wallets" section. Should be at least specified which wallets are for mobile. Only listing the supported platforms for each wallet is not enough imo.

2024-07-12 08:05 UTC, erciccione commented on get-firo/download/index.html
> +                            <p class="changelog"><a href="https://github.com/firoorg/campfire/releases/latest" target="_blank">{% t download.changelog %}</a></p>
I'm confused about Campfire. I see that the repo is on Firo's organization on github, but the play store and apple store are linking to cypherstack's original version.

There are 2 versions of this wallet: cypherstack's and firo's fork. It's very important to not be confusing about this and to clarify from which repository the public builds come from and will come from in the future. Right now the feeling is that the desktop releases come from Firo's repo and the mobile releases from Cypherstack, but i doubt that's the case.

2024-07-12 08:17 UTC, closed without merging